#!/bin/bash

# ==============================================================================
# wasta-backup-udev

#   This script launches wasta-backup-usb-autolaunch.  The reason for this
#       wrapper script is because udev must not be held up or else the USB
#       device is not ever mounted.  The mount needs to be finished to determine
#       the owner of the device in order to know the x-display-server to launch
#       wasta-backup on.
#
#   2013-06-24: Initial script
#   2013-08-12: removed .sh extension to comply with debian packaging standard
#   2015-11-04 rik: using "at" run dependent script, otherwise using 15.10
#       even though this script finishes, the automount of the usb is held
#       until the dependent script finishes as well.
#   2015-11-12 rik:  account for machines that have "broken at" due to
#       remastersys throwing away the config file /var/spool/cron/atjobs/.SEQ
#       Without that file, at doesn't work and autolaunch is broken. Fixed
#       by running "sudo dpkg-reconfigure at", but patching here so if that
#       file isn't found, we revert to the old method of launching wasta-backup.
#       WARNING: if using 15.10+ and that file doesn't exist, the old method
#       is used, then automount of ALL USBs is broken.  So we need to ensure
#       that wasta-remastersys properly configs "at" in the firstboot script.
#
# ==============================================================================

if ! [ -e /var/spool/cron/atjobs/.SEQ ]; then
  /bin/bash -c "/usr/bin/wasta-backup-usb-autolaunch $*" &
else
  echo "/usr/bin/wasta-backup-usb-autolaunch $*" | at now
fi

exit 0
