#!/bin/bash

# ==============================================================================
# wasta-backup-udev

#   This script launches wasta-backup-usb-autolaunch.  The reason for this
#       wrapper script is because udev must not be held up or else the USB
#       device is not ever mounted.  The mount needs to be finished to determine
#       the owner of the device in order to know the x-display-server to launch
#       wasta-backup on.
#
#   2013-06-24: Initial script
#   2013-08-12: removed .sh extension to comply with debian packaging standard
#   2015-11-04 rik: using "at" run dependent script, otherwise using 15.10
#       even though this script finishes, the automount of the usb is held
#       until the dependent script finishes as well.
#
# ==============================================================================

echo "/usr/bin/wasta-backup-usb-autolaunch $*" | at now

exit 0
